package-lock.json
package.json
server/models/User.model.js

Tomas: Completed the User model.js and installed pg and pg-hstore to package.json

[Feat] Completed the User model.js and installed pg and pg-hstore to package.json

---

server/models/Chats.model.js

Tomas: Completed the chat.model.js file

Tomas: Completed the chat.model.js file

---

server/models/Messages.models.js

Tomas: Completed the messages model.js

Tomas: Completed the messages model.js

---

components/LoginPage.jsx

Created a components folder so we are making multiple while we are coding

Created a components folder

---

pages/LoginPage.jsx

 Added pages folder to code

---

.eslintrc.cjs
src/App.jsx

worked on settings page UI, gave the related path in app.jsx file

 Mounika: worked on settings page UI, gave the related path in app.jsx file

---

package.json
scripts/seed.js

Created scripts folder and added seed.js with some code, there is no data yet that will seed the database and also created the chats psql in the terminal

Seed.js folder and created  chats table in PSQL

---

scripts/data/seed.json
scripts/seed.js
server/models/User.model.js
src/modals/CreateAccountModal.jsx
src/pages/LoginPage.jsx
src/pages/SettingsPage.jsx

Added a data folder inside of scripts with a seed.json file that contains dummy data to seed DB; worked on seed.js and was able to seed the DB; added some more tailwind features on the login page

Was able to seed the Database

---

src/pages/SettingsPage.jsx

created modal for EmailUpdate & worked on eventHandlers on settings page

---

src/modals/ChangeEmail.jsx
src/modals/ChangePassword.jsx
src/pages/SettingsPage.jsx

Change password 

---

src/pages/SettingsPage.jsx

 removed duplicate imports

---

src/App.jsx
src/pages/WelcomePage.jsx

Created the welcomepage.jsx file and added a route to app.jsx to render the page

Started to work on work on the welcome page after logging into your account

---

server/models/index.js
server/routes/auth.routes.js
server/routes/index.js
src/pages/LoginPage.jsx
src/pages/SettingsPage.jsx

created custom hooks for the modals, worked on login page & settings page

 created custom hooks for the modals, worked on login page & settings page 

---

server/routes/createAccount.routes.js
src/hooks/useOpenCloseModal.jsx

 routes & custome hooks

---

src/components/Input.jsx
src/modals/CreateAccountModal.jsx
src/pages/LoginPage.jsx

Made changes tailwind changes to the login page and create account modal page

Tomas: Tailwind Changes to login page and create account Modal

---

Mreadme.md
package-lock.json
package.json
reducer.jsx
src/components/Input.jsx
store.js

Reduxsetup

---

src/pages/WelcomePage.jsx

Added a button on welcome page to take you to Settings page

Added a button on welcome page to take you to Settings page

---

src/components/Input.jsx

removed the spread operator{...props} passed placeholder as prop value. the spread operator comes handy when we have too many prop values.

removed the spread operator{...props} passed placeholder as prop value

---

server/scripts/data/seed.json
src/components/Avatar.jsx
src/components/CallImage.jsx
src/pages/WelcomePage.jsx

PairProgramming: worked on welcomePage message division, created components to svg files; seeded few more users

message div, svg components, seeded data

---

Mreadme.md
package-lock.json
package.json
particles.config.js
src/App.jsx
src/components/ParticlesBackground.jsx

installed required packages; created component (ParticlesBackground.jsx); kept all the Json requred for particleJs in particles.config.js file

Mounika: worked on background animation with particleJS;

---

particles.config.js
src/App.jsx
src/components/ParticlesBackground.jsx
src/pages/WelcomePage.jsx

created a component for particlesJS

React particles

---

src/modals/ChangeUserName.jsx
tailwind.config.js

added screens object to the tailwind config file from tailwindCSS Docs

added screens object to the tailwind config file

---

src/App.jsx
src/components/Input.jsx
src/pages/LoginPage.jsx
tailwind.config.js

Added extra tailwind responsive screen, also made some changes to login page based on the size of screen

 Added extra tailwind responsive screen, also made some changes to login page based on the size of screen

---

src/components/Input.jsx
src/modals/CreateAccountModal.jsx
src/pages/LoginPage.jsx

Worked on the responsive side of the login page

Worked on the responsive side of the login page

---

server/config/db.js
server/routes/createChat.routes.js
server/routes/index.js
src/redux/reducer.js

wrote an endpoint for create chat and imported in index.js and tested the route using postman. the route is working successfully & added a LOG_OUT case in reducer

wrote an endpoint for create chat and imported in index.js and tested the route in postman

---

server/models/Chats.model.js
server/routes/createChat.routes.js
server/scripts/seed.js

changes sender&receiver to senderId&receiverId. wrapped the chatcreationapi logic in try catch block

changes sender&receiver to senderId&receiverId. wrapped the chatcreationapi logic in try catch block

---

src/pages/Responsive/SettingsPageResponsive.jsx

Added some functionality to the responsive settings page, added buttons to the screen and modals pop up when clicking the buttons

More features added to the Responsive Settings page

---

server/routes/getMessages.routes.js
server/routes/index.js

worked on gettingMessages Api need to check with the route with postman

 worked on gettingMessages Api need to check with the route with postman

---

src/pages/Responsive/SettingsPageResponsive.jsx
src/pages/WelcomePage.jsx

Added a backspace arrow to settings page for responsive side; still need to work on the logic so the username, email and password is updated when you change it

Added some features on the settings page responsive

---

server/app.js
src/pages/WelcomePage.jsx

Got the websocket.io to start working again with the new port numbers

Got the websocket.io to start working again with the new port numbers

---

src/components/Logout.jsx
src/components/Settings.jsx
src/pages/WelcomePage.jsx

created components for logout and settings buttons to make sure they work with the responsiveness of the page

created components for logout and settings buttons to make sure they work with the responsiveness of the page

---

server/app.js
src/pages/WelcomePage.jsx

Got the server to start working again; had to play around with the ports and got Diego to help with this issue

Got the server to work again

---

src/components/Logout.jsx
src/components/Settings.jsx
src/pages/WelcomePage.jsx

Added the useNavigate import to both the settings and logout components; both buttons are now working properly on the site

UseNavigate on buttons

---

src/modals/NewMessageModal.jsx
src/pages/WelcomePage.jsx

Made a new Message modal file; and implemented the modal on the welcome page and it renders when you click on the new message button

New Message Modal 

---

src/components/Chats.jsx
src/components/FriendsList.jsx
src/components/Messages.jsx
src/pages/WelcomePage.jsx

made chats,Messages,FriendsList components from welcomepage to keep the code clean

PairProgramming:  made chats,Messages,FriendsList components from welcomepage to keep the code clean

---

src/components/FriendsList.jsx
src/modals/NewMessageModal.jsx
src/pages/WelcomePage.jsx

Made the newMessage Modal looks a little better; made it into a smaller box and added an X button, search bar and compose message icon; still need to do a lot more work on this

Improvements to the New Message Modal 

---

server/routes/createMessage.routes.js
server/routes/getMessages.routes.js
src/pages/WelcomePage.jsx

edited some business logic in create message API.

edited some business logic in create message API

---

server/routes/allUsers.routes.js
server/routes/index.js
src/App.jsx
src/components/Chats.jsx

Made a new route to get all the users from the DB; used that endpoint to display that data on the Chats.jsx file

Users appear in Welcome Page

---

src/components/Chats.jsx

Fixed the merge conflict on the Chats.jsx file and added some tailwind styles to the "Chats" header

Fixed the merge conflict on the Chats.jsx file

---

src/components/Chats.jsx
src/components/FriendsList.jsx
src/components/Logout.jsx
src/components/Settings.jsx
src/modals/NewMessageModal.jsx

Got the user's data to show up on the Friends List side; also added some border under each user to identify where to click on when the messaging part works; made the logout and settings buttons next to each other rather than on top of each other; still need to work on the new message modal and group chat modal

More improvements on the welcome page

---

src/components/Chats.jsx
src/components/FriendsList.jsx
src/modals/GroupMessageModal.jsx
src/modals/NewMessageModal.jsx
src/pages/SettingsPage.jsx

Made some changes to the new message modal page to display the users info; still need to work on the group message modal

New Message Modal changes

---

src/components/Chats.jsx
src/components/FriendsList.jsx

Pair Programming: Worked on the the chats.jsx file and the user data appear more cleanier; will add the most recent messages at a later time; need to work on the friends list user data as well

Pair Programing; made changes to chats.jsx file

---

src/modals/ChangeEmail.jsx
src/modals/ChangePassword.jsx
src/modals/ChangeUserName.jsx
src/pages/Responsive/SettingsPageResponsive.jsx
src/pages/SettingsPage.jsx

Got the settings page reorganized and to display users data expect for the password; still need to test if the data email, username, and password get updated properly in the database

Updated the settings page

---

server/models/Chats.model.js
server/models/index.js
server/routes/createMessage.routes.js
server/routes/getChat.routes.js
src/App.jsx
src/components/Avatar.jsx
src/components/Chats.jsx
src/components/FriendsList.jsx
src/components/Logout.jsx
src/components/Messages.jsx
src/components/UserIcon.jsx
src/main.jsx
src/pages/LoginPage.jsx
src/pages/WelcomePage.jsx
src/redux/actionTypes.js
src/redux/chatActions.js
src/redux/friendsActions.js
src/redux/messageActions.js
src/redux/reducer.js

all the routes working fine.deleted existing chats and users from DB.added actions to reducer.js as we are using redux for state management.able to get that chats and messages from the APIs and dispatch through axios

tested createChat,getChat,createMessage,getMessages APis with postman

---

server/routes/createMessage.routes.js
src/components/Chats.jsx
src/components/FriendsList.jsx
src/components/Input.jsx
src/components/Messages.jsx
src/redux/reducer.js

tried to create message from input by using useRef and implimented onClick functionality to dispaly the messages in the message area

 tried to create message from input and implimented onClick functionality to dispaly the messages in the message area

---

src/components/Messages.jsx
src/components/UserIcon.jsx

User Icon color now give fixed colors instead of random colors on refresh. Did some ui changes in the Message.jsx component.

User Icon color fixes

---

server/routes/auth.routes.js
server/routes/userSettings.routes.js
src/App.jsx
src/components/Chats.jsx
src/components/FriendsList.jsx
src/components/Input.jsx
src/components/Messages.jsx
src/components/ParticlesBackground.jsx
src/components/UserIcon.jsx
src/hooks/useOpenCloseModal.jsx
src/modals/CreateAccountModal.jsx
src/pages/Responsive/ChatPageResponsive.jsx
src/pages/Responsive/SettingsPageResponsive.jsx
src/pages/SettingsPage.jsx
src/pages/WelcomePage.jsx

Made the app more responsive and got the password to hash when it is being updated in settings

Made app more responsive
